package com.kilobolt.GameWorld;


public class Quiz {

	String Question = "";	
	public Quiz(){
		
	}
	
	public boolean[] doneQ={false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
							 false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};
	public int ansA[]={0,1,1,0,0,0,1,1,1,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,
			0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,
			0,0,0,0,1,1,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,1,0,0,0,
			1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,0,0,1,0,1,0,0,1,1,0,0,1,1,0,1,1,0,1,0,0,1,
			0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0,0};
			
	public int ansB[]={1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,1,1,0,0,0,1,1,0,1,
			1,0,1,0,1,1,0,1,0,0,0,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,0,1,
			1,1,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,
			0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,
			1,1,1,0,0,1,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,1,1,1,1,0,1,0};
			
	public int ansC[]={0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,1,1,0,0,0,0,
			0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,1,1,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,
			0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,1,0,0,1,0,1,1,1,1,0,0,0,0,0,0,1,0,1,1,0,
			0,0,0,1,0,0,0,0,1,1,0,0,1,0,1,0,1,0,0,1,1,0,1,0,1,1,0,0,1,1,0,0,1,0,0,1,0,0,0,0,
			0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1};

	public String[] Questions={"The oceans cover ______ of the Earth's surface.",
			"Which ocean is the largest?",
			"Which ocean basin is the most geologically active?",
			"How does water move around the world?",
			"Ocean water moves:",
			"What are thermohaline currents?",
			"What type of water is more dense?",
			"What are basalts?",
			"What are the abyssal plains?",
			"What property of water does salt alter?",
			"What are the main categories of sea life?",
			"What are phytoplankton?",
			"What are zooplankton?",
			"What are examples of benthos?",
			"What type of creatures live near hydrothermal vents in the deep sea?",
			"What sea life is at the very bottom of the food chain?",
			"What do sea sponges eat?",
			"What sea creature may have cancer-fighting properties?",
			"Where does offshore oil drilling occur?",
			"In what year was the Gulf Stream discovered?",
			"What is the approximate temperature of the deep ocean?",
			"About how many new plant and animal species did researchers find during the Challenger Expedition?",
			"What percentage of the world's volcantic" +"activity occurs within the oceans?",
			"Who named the Gulf Stream?",
			"Which oceanographer's last film documented" +"the effects of the Exxon Valdez oil"+" spill in Alaska?",
			"If you study chemical elements in seawater,"+" you're practicing which branch of"+" oceanography?",
			"How did the first researchers determine ocean depths?",
			"In feet, what's the greatest difference "+"between high and low tides anywhere on Earth?",
			"How many tons of water flow in and out of "+"the Bay of Fundy during one tide cycle?",
			"Which explorer-oceanographer finally explained"+" the reason for \"dead water?\"",
			"What is NOT a primary contributing factor to ocean currents?",
			"Which oceanographic institution came first?",
			"What is El Nino?",
			"A company in which country developed Deepsea Challenger,"+" which was built to dive to the deepest spot"+" on Earth?",
			"Rising ocean temperatures account for what percentage"+" of energy accumulation from"+" global warming?",
			"Which country has the longest ocean coastline?",
			"How many sonar measurements did the German Meteor"+" expedition use to document the Mid-Atlantic ridge?",
			"Mary Sears was a Navy commander and oceanographer"+" who spent many years studying which creatures?",
			"What was the name of one of the first oceanographical texts ever published?",
			"In what year did Matthew Maury publish his groundbreaking "+"text, \"Physical Geography of the Sea?\"",
			"What is the record for the tallest iceberg?",
			"What tools do oceanographers often use to predict "+"El Nino-related phenomena?",
			"Which explorer-oceanographer earned the nickname"+" \"The Sturgeon General?\"",
			"What ocean feature did Bruce Heezen and "+"Maurice Ewing discover in 1953?",
			"Oceanographers blame ocean acidification on what?",
			"Which oceanographer made important observations"+" regarding ocean circulation?",
			"Where does a venomous creature usually acquire its poison?",
			"What is common to different venomous creatures?",
			"Which marine creature has the deadliest venom?",
			"How long does it take for the box jellyfish venom"+" to kill a human?",
			"Just how much venom does this deadly creature have?",
			"What happens when you try to shake the stingers off?",
			"Is there an effective first aid prior to medical treatment?",
			"How do some Australians avoid jellyfish stings?",
			"What is an inland taipan?",
			"Is the coral a plant?",
			"What does 'sessile' mean?",
			"Why did scientists originally think corals were plants?",
			"What is common to the jellyfish, sea anemone and the coral?",
			"Since it cannot move from place to place,"+" how does the coral hunt for prey?",
			"Why could you consider a coral a half-plant?",
			"What do algae gain from coral?",
			"What is the substance the polyps secrete?",
			"How many polyps can be found in a single branching coral?",
			"When polyps join together into a colony what happens to them?",
			"Do polyps reproduce?",
			"How is a new colony formed?",
			"What do coral reefs need to survive and flourish?",
			"How do most mantis shrimp live their lives?",
			"What is the defining trait of mantis shrimp?",
			"Other than vicious weapons, what other standout"+" characteristic do mantis shrimp have?",
			"Why does this shrimp have \"mantis\" in its name?",
			"The mantis shrimp belongs to which order?",
			"How big do the largest mantis shrimp grow?",
			"How many color-receptive cones do mantis shrimp eyes contain?",
			"Compared to humans, how many more colors can a mantis shrimp detect?",
			"How many species of mantis shrimp are there?",
			"The mantis shrimp can be traced how far back into fossil history?",
			"How fast is the mantis shrimp's ability to"+ " strike with its hammer or spear?",
			"Why do some female mantis shrimp have to lay two "+"clutches of eggs instead of one?",
			"How do mantis shrimp fight each other over territory?",
			"Which set of appendages develops into the weapons "+"that the shrimp uses to kill prey?",
			"What's the longest that some mantis shrimp live in the wild?",
			"At what speed does the shrimp unleash its hammer weapon?",
			"How many creatures on Earth can create circular "+"polarization with their visual system?",
			"The taste of mantis shrimp flesh is often compared to what?",
			"How does a mantis shrimp process all of the visual "+"information collected by its eyes?",
			"As time goes by, what happens to the mantis shrimp\'s clublike weapon?",
			"What's one reason that the shrimp\'s eyes process "+"visual information instead of the brain?",
			"Why do many aquarists avoid keeping mantis shrimp as pets?",
			"What is the common factor uniting spiders, wood lice and crabs?",
			"How many species of crustaceans are there?",
			"How many segments can there be in a crustacean\'s body?",
			"As the crustacean grows, how does the chitin develop?",
			"How does the crustacean find its way?",
			"If the crustacean uses its claws for grasping and eating,"+" how does it walk?",
			"How many segments does the body of the lobster have?",
			"How do land-dwelling crustaceans contribute to agriculture?",
			"What do lobsters, sandhoppers and wood lice have something in common?",
			"In what part of the world are barnacles a delicacy?",
			"For what type of cuisine is the crayfish the main ingredient?",
			"Which marine creature enjoys a meal of krill?",
			"What are the smallest crustaceans?",
			"Of all the crustaceans, which are the most common?",
			"Are crustaceans in any danger?",
			"What is the average size of lobsters caught today?",
			"Lobsters are related to:",
			"Lobsters are caught in:",
			"What type of lobster is sold commercially to the general public?",
			"What part of North American do people typically catch American lobster?",
			"How do fisherman catch American lobster?",
			"Where do most lobsters typically live in the ocean?",
			"Where do spiny lobsters live in the ocean?",
			"How much does a typical American lobster weigh?",
			"What color are American lobsters?",
			"The exoskeleton of an American lobster:",
			"Where is the thickest part of an American lobster?",
			"A lobster has ____ pairs of legs.",
			"The abdomen of a lobster is composed of:",
			"What part of the spiny lobster is edible?",
			"Lobsters have internal organs similar to those of a(n):",
			"The lobster\'s shell is:",
			"What happens if a lobster loses a claw or leg?",
			"Lobsters mature after:",
			"What is the purpose of a lobster's antennae?",
			"A male pillow octopus is ______ a female pillow octopus.",
			"How do pillow octopuses mate?",
			"What does an octopus feel like?",
			"Octopuses use their arms for:",
			"Octopuses are related to:",
			"Why are octopuses referred to as cephalopods?",
			"Octopuses have:",
			"What is found inside an octopus\'s mantle?",
			"How do octopuses protect themselves from predators?",
			"What color is octopus blood?",
			"How many hearts does an octopus have?",
			"Chromatophores allow an octopus to:",
			"How quickly can an octopus change color?",
			"What are iridophores?",
			"An octopus\'s eyesight is:",
			"An octopus\'s brain is:",
			"An octopus\'s arms are mainly composed of:",
			"Octopuses are:",
			"What is the activity level of a typical octopus?",
			"A typical octopus lives for:",
			"Oysters are related to:",
			"Where do oysters live?",
			"Humans have been eating oysters since:",
			"When do oysters lose their taste?",
			"What color are oyster shells?",
			"Oyster shells are made out of:",
			"What keeps an oyster shell closed?",
			"What is the purpose of an oyster\'s gills?",
			"What does an oyster lack?",
			"Which of the following is a predator for the oyster?",
			"What do oysters eat?",
			"How do oysters reproduce?",
			"How old are oysters when they are harvested by fisherman?",
			"What type of oysters have deep-cupped shells?",
			"How can you tell the age of an oyster?",
			"What happens as an oyster's body grows?",
			"Where in the world are oysters cultivated?",
			"What happens when an oyster is shucked?",
			"What's the largest animal on Earth?",
			"What marine mammal is referred to as"+" the \"wolf of the sea\"?",
			"What do baleen whales lack that other whales have?",
			"What's the longest amount of time that "+"whales can go without breathing?",
			"What are narwhal tusks made of?",
			"What special sense do dolphins and some "+"whales use to hear underwater?",
			"Which body part of a walrus is most useful for hunting?",
			"What's the easiest way to tell the difference"+" between true seals and sea lions?",
			"\"Floating gold\" is another name for "+"what marine mammal excretion?",
			"Which of the following is a difference "+"between dolphins and porpoises?",
			"How many different whale species are out there?",
			"What are the two main types of whales?",
			"What is the largest of the toothed whales?",
			"What part of the sperm whale is unusually large?",
			"Which whales are called the canaries of the sea?",
			"Where does the gray whale prefer to dine?",
			"Which of these body parts is unique to the beluga whale?",
			"What color are beluga whales?",
			"What do blue whales prefer to eat?",
			"Roughly how many blue whales are alive today?",
			"What feature is the humpback whale known for?",
			"Is the humpback whale a baleen or odontocetes?",
			"Which of these is the largest member of the dolphin family?",
			"What color is the killer whale?",
			"What type of whale is known for its white chin?",
			"Where do bowhead whales prefer to live?",
			"What percentage of the length of the bowhead whale"+" is made up of its skull?",
			"What is the second largest whale species?",
			"How long can the fin whale get?",
			"How many different species of baleen whale are there?",
			"How many species of toothed whales are known to exist?",
			"How many species of beaked whales can be found?",
			"What is the smallest species of baleen whale?",
			"Where do narwhals typically live?",
			"What is the range in length of the whale species?",
			"What is the common name given to the two wings on a whale’s tail fin?",
			"What portion of a whale’s total body length is its tail?"};	
	public String[] ChoiceA_List={"60 percent","Pacific ocean","Pacific ocean","Wind","From north to south",
			"Cold water currents from the arctic","Polar, cold water","Volcanic rocks on the ocean floor","Flat areas of the ocean floor",
			"Freezing point","Swimmers and non-swimmers","A larger version of plankton","Small worms and jellyfish","Lobsters",
			"Worms","Phytoplankton","Phytoplankton","Sponge","The Persian Gulf",
			"1221","39 degrees Fahrenheit","1,500","90%","Columbus",
			
			"Sylvia Earle","Biological oceanography","They refracted light into the depths.","Eight feet","40 billion tons",
			"Matthew Maury","Tides","Virginia Institute of Marine Science","A surge of cold water that dips into the Atlantic Ocean about every four years.","Australia",
			"50%","United States","20,000","Sardines","Physical Geography of the Sea",
			"1832","380 feet","Radar","Robert Ballard","The Mid-Ocean Ridge",
			"Industrial waste, mostly from power generation","Alfred Wegner","From what they eat","Lying in wait for prey","Portuguese Man-of-War",
			
			"Five minutes","20 adults","The tentacles contract and stick tighter.","Carbonated soft drink","They rub insect repellant on their skin before entering the water.",
			"Venomous cone snail","It's a living creature.","It's a creature that lies in wait for prey.","They had never seen a living creature attached to a substratum.","Carnivorous",
			"The coral emits secretions that attract marine life which it swallows when in range.","Algae living in he coral's cell walls provide products the coral turns into nutrients.","The algae feed on scraps of undigested fish bones.","Calcium carbonate","Hundreds",
			"Each polyp continues to operate individually from a common location.","By producing identical clones (asexually)","Strong underwater currents cause corals to break away and drift to a new location.","Sunlight and warm salty water","In small groups",
			"Their relative intelligence","Highly evolved feet","Its mouth is shaped like that of a praying mantis.","Echinozoa","About 8 inches (20 centimeters)",
			
			"Sixteen","Four times as many","About 100","About 30 million years","50 times as fast as a blink of an eye",
			"So that she has something to eat during the offspring's larval stage","They treat each other like prey.","First set","18 months","30 feet per second (9 meters per second)",
			"One","Lobster","In the eye","It breaks down.","Speed",
			"They are too violent.","Six legs","25000","Less than 40","It hardens and expands.",
			"Using appendages attached to the thorax","Claws are also used for walking.",	"50","They are vital to the fertilization of crops.","All give birth to their eggs on dry land.",
			
			"Parts of Europe and South America","Thai","Sea bass","Water fleas","Pill bugs",
			"All are in danger.","20 pound (9 kilogram)","Crayfish","The Pacific ocean","American lobster",
			"California","In traps","In shallow water","In coral reefs","Two pounds",
			"Pink","Is fused together","The back","Three","A hard shell",
			"The entire lobster","Human","Permanent and never replaced","It's deformed for life.","One year",
			
			"They detect predators.","Lighter than","The male octopus has sperm in his arm.","A snake","Moving around",
			"Clams","Because they have many long arms","Only arms","Hearts","Camouflage",
			"Red","Two","Reproduce","Less than a second","Reflective cells",
			"Non-existent","Very small","Muscle","Nomadic","Very lazy",
			"A few years","Scallops","At the bottom of the ocean","Prehistoric times","From September to December",
			
			"Gray","Calcium","The abductor muscle","For collecting food","A head and brain",
			"Marine snails","Debris","By releasing eggs or sperm into the water","One year old","Pycnodonta oysters",
			"By their rings","The oyster sheds its shell for a larger one.","In North America only","It's washed with soap.","Blue whale",
			"Narwhal","Eyes","20 minutes","Ivory","Passive sonar",
			"Eyes","Look at the whiskers.","Whale vomit","Porpoises are considered toothed whales, while dolphins aren't.","13",
			
			"Toothed and nontoothed","Killer","Head","Sperm","On the beach",
			"Massive thick skull","White","Humans","500","Tail fin",
			"It depends.","Killer whale","Gray","Bowhead","Tropical climates",
			"20-30 percent","Fin whale","55 feet (17 meters)","Three","30","12",
			"Orca","Tropical waters","From 5 feet to more than 100 feet","Sails",	"one eighth"};
	public String[] ChoiceB_List={"70 percent","Atlantic ocean","Atlantic ocean","Gravity","From south to north","Warm water currents from Africa","Equator, hot water","Volcanic eruptions under the water","Mountainous areas of the ocean floor","Boiling point","Swimmers, floaters and creatures on the sea floor","Organisms that eat plankton","Clams",
			"Small fish","Fish","Microscopic fish","Plankton","Sea-squirt",
			"The North Sea","1513","42 degrees Fahrenheit","4,700","70%",
			"Juan Ponce de Leon","Jacques Cousteau","Physical oceanography","Rope and lead weights","31 feet",
			"160 billion tons","Fridtjof Nansen","Wind","International Council for the Exploration of the Sea",	"An occasional shift of warm water from the western to eastern Pacific Ocean.",
			"Japan","70%","Russia","70,000","Plankton",
			"The Sea","1855","550 feet","Nuclear submarines","Sylvia Earle",
			"The biggest underwater volcano","Human-caused carbon dioxide","Henry Stommel","Produce it themselves","Means of delivering the venom",
			"Hydra","Ten minutes","40 adults","The tentacles back off but the stingers can rip your skin while retreating.","Cold fresh water",
			"They wear women's pantyhose when swimming.","Deadly snake","It is a sophisticated fish-eating plant.","It is an asexual creature.","The tentacles of the coral look like tree branches.",
			"All are protected species","The tentacles send out an electric charge paralyzing small fish.","The coral is implanted in the reef.","The coral supplies carbon, nitrates and phosphates.","Phosphate",
			"Thousands","They form larger working groups competing with the other groups.","By sending out eggs or sperm (sexually)","Newly created polyps settle downwards until they reach a hard surface.","Cool water rich in nutrients",
			"In large groups","Their powerful claw","Complex eyes","It is just as aggressive as a praying mantis.","Veneroida",
			"About 15 inches","Eight","Eight times as many","About 450","About 100 million years",
			"10 times as fast as a blink of an eye","So the male can take care of one","They scuffle.","Second set","Three years",
			"75 feet per second","Three","Shrimp","In the brain","It gets sharper.",
			"Lack of intelligence","They eat just about everything.","Venomous stings when threatened","5000","Up to 50",
			"The overlapping panels increase in number.","Using its compound eyes","Walks on legs attached to abdomen.","35","They prevent destruction of crops by insects and other pests.",
			"All have 19 body segments.","China and Japan","Indian","Whales","Wood lice",
			"Krill","Most are not in danger.","10 pound (4.5 kilogram)","Shrimp","The Atlantic ocean",
			"Marine crayfish","Nova Scotia","In nets","In deep water","In sand",
			"Five pounds","Dark green","Has moveable parts","The head","Four",
			"A soft, flexible shell","The lobster tail","Insect","Shed frequently when young","It grows a new claw or leg.",
			"Two years","They detect food.","Heavier than","They mate with typical sex organs.","The inside of your cheek",
			"Tasting","Snails","Because their arms protrude out of their head","Arms and tentacles","Digestive system",
			"A hard protective shell","Green","Three","Regenerate arms","Less than a minute",
			"Color cells","Mediocre","Highly evolved","Fatty tissue",	"Nocturnal",
			"Somewhat active","Many years","Mussels","On coral reef","Biblical times",
			"From January to April","Whitish","Iron",	"The mantle","For breathing",
			"A mouth","Small fish","Plankton","By making contact with the opposite sex","Three to five years old",
			"Crassostrea  oysters","By their spots","The shell also grows.","All over the world","The shell is removed.",
			"Humpback whale","Manatee","Teeth","75 minutes","Calcium",
			"Echolocation","Tusks","Look at the ears.","Walrus sweat",	"Porpoises have rounded, blunt muzzles, and dolphins have pointed ones.",
			"70","Finned and nonfinned",	"Blue","Tongue","Beluga",
			"At the surface","Heavy layer of blubber","Blue",	"Squid","5,000",
			"Pectoral fin","Odontocetes","Gray whale","Blue","Sperm","Moderate climates",
			"30-40 percent","Gray whale","85 feet","Seven","70","22",
			"Minke","Arctic waters","From 10 feet to more than 120 feet","Flukes","One quarter"};
	public String[] ChoiceC_List={"90 percent",	"Indian ocean",		"Indian ocean",		"Both of the above",		"In a circular pattern",
			"Currents that move up and down in the ocean",		"Water close to the shore",		"Volcanic ash found in the ocean",		"Rocky and gagged areas of the ocean floor",		"Both of the above",
			"Fish, mammals and microscopic creatures",		"Microscopic algae",		"Both of the above",		"Shrimp",		"Both of the above",
			"Both of the above",		"Waste products from other fish",		"Both of the above",		"Both of the above",		"1698",
			"45 degrees Fahrenheit",		"6,200",		"50%",		"Benjamin Franklin",		"Robert Ballard",
			"Chemical oceanography",		"They attached rope to a large fish and released it.",		"53 feet",	"220 billion tons",		"Vagh Ekman",
			"Salinity",		"Scripps Institution of Oceanography",		"Increasingly warm waters in the Gulf of Mexico that dramatically shift weather patterns.",		"United States",		"90%",
			"Canada",		"1 million",		"Tuna",		"The Underwater World",		"1898",
			"890 feet",		"A collection of buoys",		"James Cook",		"Mariana Trench",		"Nuclear waste dumped into the sea in the early 1980's",
			"Mary Sears",	"Produced during mating season",		"Immunity to venom of other creatures",		"Box jellyfish",	"Fifteen minutes",
			"60 adults",	"The stingers detach from the nematocysts and are driven far beneath the surface of your skin.",	"Vinegar",	"They trail ribbons behind them to distract the jellyfish's tentacles.",	"Freshwater jellyfish",
			"It defies precise definition because of its unique nature.",		"It means fixed in place.",	"There was no evidence of a breathing mechanism necessary to sustain life.",	"All exist exclusively in tropical waters",	"Its tentacles wait until something small and tasty brushes past.",
			"The tentacles are identical to parts of certain plants that entrap insects.",		"The algae feed on plant growths that irritate the coral.",		"Sodium chloride",		"Tens of thousands",		"They all work together as a single organism.",
			"By dividing thereby producing identical clones (asexually) and by sending out eggs or sperm (sexually)",	"Large fish break off pieces of coral which they dump when can't digest it.",	"Fewer fish nibbling away at the reef",		"Alone",	"Their running speed",		
			"Humanlike blood",			"It tucks appendages under its body like a praying mantis.",		"Stomatopod",
			"About 20 inches",		"Five",		"10 times as many",		"About 620",		"About 250 million years",
			"Five times as fast as a blink of an eye",		"So she can scurry back and forth between the two",		"They trick each other.",		"Third set",		"20 years or longer",
			"90 feet per second",		"Six",		"Chicken",		"In the brain stem",		"It becomes articulated.",
			"Sea water effects the brain",			"They are hard to care for.",		"Membership of same division of the animal world",		"1000",		"60",
			"It is periodically shed and a new one grows.",
			"Sensory nerves on the claws",			"It doesn't walk, it swims.",			"19",		"Most are pests.",		"All are exclusively herbivores.",
			"India and Thailand",		"Cajun",		"Lobsters",		"Pill bugs",		"Copepods",
			"Only the fresh water ones are endangered.",		"1 pound (0.45 kilogram)",			"Both of the above",		"Both of the above",		"Both of the above",
			"Florida",			"Both of the above",		"Both of the above",	"Both of the above",		"Seven pounds",		"Dark brown",
			"Both of the above",			"The legs",			"Five",		"Shell rings",		"The lobster legs",
			"Fish",		"Only grown in adulthood",		"It's killed by other lobsters.",		"Four years",		"Both of the above",
			"The same weight as",		"The male octopus has sperm in his head.",	"128 no C answer",		"Both of the above",	"Both of the above",
			"Both of the above",	"Arms and antennas",	"Both of the above",	"Poisonous arms",	"Blue",
			"Four","Change color",	"Less than a hour",	"Receptor cells","Very good",
			"Both of the above","Nerves","Both of the above","Hyperactive","A few decades",
			"Both of the above","Both of the above","Medieval times","From May to August","Both of the above",
			"Copper","The shell-secreting membrane",	"Both of the above","Both of the above","Both of the above",
			"Both of the above","Aoth of the above",	"About ten years old",	"Ostrea oysters","By their shell thickness",
			"Both of the above","In North American and Asia only",	"Hormones are inserted to increase size.",	"Whale shark","Orca",
			"Blowholes","Two hours","Limestone","Lateral line",	"Whiskers",
			"Look at the size of the body.","Dolphin feces",	"Porpoises are shier than dolphins.",	"170","Killer and nonkiller",
			"Sperm","Tail",	"Blue",	"At the bottom of the sea",	"Nonfused neck",
			"Black","Krill","5 million","Large head","Baleen",
			"Humpback whale","Black and white","Blue","Icy climates",	"40-50 percent",
			"Beaked whale","125 feet","13","90","34",
			"Vaquita","On the Australian coast",	"From 15 feet to more than 130 feet",	"Vestigial flaps","One third"
	};

	public String getQuestion(int qns){
		return Questions[qns-1];
	}
	public String getChoice1(int qns){
		return ChoiceA_List[qns-1];
	}
	public String getChoice2(int qns){
		return ChoiceB_List[qns-1];
	}
	public String getChoice3(int qns){
		return ChoiceC_List[qns-1];
	}
	
	
}